(function(g){var window=this;var Qja=function(a,b){return g.dc(a,b)},Rja=function(a){if(a.hc&&"function"==typeof a.hc)return a.hc();
if(g.v(a))return a.split("");if(g.Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.$b(a)},Sja=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ba(a)||g.v(a))(0,g.C)(a,b,void 0);else{if(a.kd&&"function"==typeof a.kd)var c=a.kd();else if(a.hc&&"function"==typeof a.hc)c=void 0;else if(g.Ba(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.ac(a);d=Rja(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},o4=function(a){g.Vo(a,"zx",g.Jb());
return a},p4=function(a,b,c){g.Aa(c)||(c=[String(c)]);
g.ap(a.o,b,c)},q4=function(){},r4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},s4=function(a){var b;
(b=a.g)||(b={},r4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},t4=function(a){return(a=r4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},u4=function(a,b){return b+" ["+a.W+" "+a.J+" "+a.getStatus()+"]"},Tja=function(a){return"content-type"==a.toLowerCase()},v4=function(a){a.g&&a.L&&(a.g.ontimeout=null);
a.F&&(g.x.clearTimeout(a.F),a.F=null)},Uja=function(a){return g.Gd&&g.Ac(9)&&g.wa(a.timeout)&&g.t(a.ontimeout)},w4=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},x4=function(a,b){if(a.g){v4(a);
var c=a.g,d=a.O[0]?g.xa:null;a.g=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},y4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;w4(a);x4(a)},z4=function(a){return a.g?a.g.readyState:0},A4=function(a){if(a.l&&"undefined"!=typeof g.yW)if(a.O[1]&&4==z4(a)&&2==a.getStatus())u4(a,"Local request error detected and ignored");
else if(a.G&&4==z4(a))g.yg(a.Sr,0,a);else if(a.dispatchEvent("readystatechange"),4==z4(a)){u4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Rg(String(a.J))[1]||null;if(!f&&g.x.self&&g.x.self.location){var k=g.x.self.location.protocol;f=k.substr(0,k.length-1)}e=!Vja.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<z4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";w4(a)}}finally{x4(a)}}},B4=function(a){g.Af.call(this);
this.headers=new g.Io;this.R=a||null;this.l=!1;this.O=this.g=null;this.W=this.J="";this.A=0;this.B="";this.o=this.X=this.G=this.T=!1;this.C=0;this.F=null;this.ca="";this.L=this.Y=!1},C4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Wja=function(a,b){var c=[];
g.vl(b,function(a){try{var b=g.Xq.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.Wq(b)&&c.push(a):c.push(a)},a);
return c},Xja=function(a,b){var c=Wja(a,b);
(0,g.C)(c,function(a){g.Xq.prototype.remove.call(this,a)},a)},D4=function(a){if(a.Kc){if(a.Kc.locationOverrideToken)return{locationOverrideToken:a.Kc.locationOverrideToken};
if(null!=a.Kc.latitudeE7&&null!=a.Kc.longitudeE7)return{latitudeE7:a.Kc.latitudeE7,longitudeE7:a.Kc.longitudeE7}}return null},Yja=function(a,b,c,d){var e=new g.Lo(null,void 0);
a&&g.Mo(e,a);b&&g.No(e,b);c&&g.Oo(e,c);d&&(e.l=d);return e},E4=function(){this.g=[];
this.l=[]},F4=function(a){g.Zt[a]&&(a=g.Zt[a],(0,g.C)(a,function(a){g.Xt[a]&&delete g.Xt[a]}),a.length=0)},Zja=function(a){var b=g.Wt();
if(b)if(b.clear(a),a)F4(a);else for(var c in g.Zt)F4(c)},G4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Io;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$ja(this,a.capabilities||""),aka(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},$ja=function(a,b){a.capabilities.clear();
(0,g.Wd)(b.split(","),g.Ja(Qja,bka)).forEach(function(b){a.capabilities.add(b)})},aka=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},H4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},I4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},J4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cka=function(a){return new H4(a)},K4=function(a){return g.Aa(a)?(0,g.E)(a,cka):[]},L4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},M4=function(a){return g.Aa(a)?"["+(0,g.E)(a,L4).join(",")+"]":"null"},N4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dka=function(a){return(0,g.E)(a,function(a){return{key:a.id,
name:a.name}})},O4=function(a,b){return g.Pa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},P4=function(a,b){return g.Pa(a,function(a){return I4(a,b)})},eka=function(){var a=(0,g.Su)();
a&&Xja(a,a.g.He(!0))},Q4=function(){var a=g.Vu("yt-remote-connected-devices")||[];
g.jb(a);return a},fka=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.E)(a,function(a,b){return 0==b?a:a.substring(c.length)})},R4=function(a){g.Uu("yt-remote-connected-devices",a,86400)},T4=function(){if(S4)return S4;
var a=g.Vu("yt-remote-device-id");a||(a=N4(),g.Uu("yt-remote-device-id",a,31536E3));for(var b=Q4(),c=1,d=a;g.Ta(b,d);)c++,d=a+"#"+c;return S4=d},U4=function(){var a=Q4(),b=T4();
g.Ta(a,b);g.Xu()&&g.ob(a,b);a=fka(a);if(0==a.length)try{g.Fu("remote_sid")}catch(c){}else try{g.Eu("remote_sid",a.join(","),-1)}catch(c){}},V4=function(){return g.Vu("yt-remote-session-browser-channel")},W4=function(){return g.Vu("yt-remote-local-screens")||[]},X4=function(){g.Uu("yt-remote-lounge-token-expiration",!0,86400)},gka=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.E)(W4(),function(a){return a.loungeToken}),c=(0,g.E)(a,function(a){return a.loungeToken});
(0,g.no)(c,function(a){return!g.Ta(b,a)})&&X4();
g.Uu("yt-remote-local-screens",a,31536E3)},hka=function(a,b){g.Uu("yt-remote-session-browser-channel",a);
g.Uu("yt-remote-session-screen-id",b);var c=Q4(),d=T4();g.Ta(c,d)||c.push(d);R4(c);U4()},Y4=function(a){a||(g.Wu("yt-remote-session-screen-id"),g.Wu("yt-remote-session-video-id"));
U4();a=Q4();g.Xa(a,T4());R4(a)},$4=function(){if(!Z4){var a=g.jr();
a&&(Z4=new g.Rq(a))}return Z4?!!Z4.get("yt-remote-use-staging-server"):!1},ika=function(){var a=window.document.createElement("a");
g.fd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Nb(a)},jka=function(a,b){var c=g.Pd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.id(c,g.ke("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},kka=function(){var a=ika(),b=window.document.getElementById(a),c=b&&g.jt(b,"loaded");
c||b&&!c||(b=jka(a,function(){g.jt(b,"loaded")||(g.it(b,"loaded","true"),g.cu(a),g.Zr(g.Ja(Zja,a),0))}))},a5=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},b5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},d5=function(a){a.length?c5(a.shift(),function(){d5(a)}):e5()},lka=function(a){return"chrome-extension://"+a+f5},c5=function(a,b,
c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},g5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},e5=function(){var a=b5();
a&&a(!1,"No cast extension found")},h5=function(){if(mka){var a=2,b=b5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;c5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",e5,c)}},nka=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(h5(),a({command:"cast.sender.init"}))},oka=function(){h5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);d5(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+f5,"//www.gstatic.com/eureka/clank"+f5])},i5=function(a,b,c){g.G.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Fc=b;this.B=(0,g.A)(this.Vz,this);this.g=!1;this.l=0;this.o=this.ya=null;this.A=[]},j5=function(){},k5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.aa=new g.bp(this);this.l=new g.xg;this.l.setInterval(250)},m5=function(a,b,c){a.oh=1;
a.yf=o4(b.clone());a.Gg=c;a.B=!0;l5(a,null)},n5=function(a,b,c,d,e){a.oh=1;
a.yf=o4(b.clone());a.Gg=null;a.B=c;e&&(a.uw=!1);l5(a,d)},l5=function(a,b){a.Lh=(0,g.D)();
o5(a);a.Rf=a.yf.clone();p4(a.Rf,"t",a.C);a.rj=0;a.dc=a.g.Hm(a.g.jj()?b:null);0<a.dn&&(a.ol=new g.Am((0,g.A)(a.Fx,a,a.dc),a.dn));a.aa.da(a.dc,"readystatechange",a.NJ);var c=a.qg?g.lc(a.qg):{};a.Gg?(a.Ql="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.dc.send(a.Rf,a.Ql,a.Gg,c)):(a.Ql="GET",a.uw&&!g.Id&&(c.Connection="close"),a.dc.send(a.Rf,a.Ql,null,c));a.g.Zd(1)},v5=function(a,b,c){for(var d=!0;!a.gg&&a.rj<c.length;){var e=pka(a,c);
if(e==p5){4==b&&(a.zf=4,q5(15),d=!1);break}else if(e==r5){a.zf=4;q5(16);d=!1;break}else s5(a,e)}4==b&&0==c.length&&(a.zf=1,q5(17),d=!1);a.be=a.be&&d;d||(t5(a),u5(a))},pka=function(a,b){var c=a.rj,d=b.indexOf("\n",c);
if(-1==d)return p5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return r5;d+=1;if(d+c>b.length)return p5;var e=b.substr(d,c);a.rj=d+c;return e},y5=function(a,b){a.Lh=(0,g.D)();
o5(a);var c=b?window.location.hostname:"";a.Rf=a.yf.clone();g.Vo(a.Rf,"DOMAIN",c);g.Vo(a.Rf,"t",a.C);try{a.ce=new window.ActiveXObject("htmlfile")}catch(n){t5(a);a.zf=7;q5(22);u5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in w5)k=w5[l];else if(l in x5)k=w5[l]=x5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
w5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.jd(g.Gc("b/12014412"),d);a.ce.open();a.ce.write(g.bd(c));a.ce.close();a.ce.parentWindow.m=(0,g.A)(a.hJ,a);a.ce.parentWindow.d=(0,g.A)(a.Gv,a,!0);a.ce.parentWindow.rpcClose=(0,g.A)(a.Gv,a,!1);c=a.ce.createElement("DIV");a.ce.parentWindow.document.body.appendChild(c);d=g.Qc(a.Rf.toString());d=g.Db(g.Nc(d));d=g.jd(g.Gc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.bd(d);a.g.Zd(1)},o5=function(a){a.Fp=
(0,g.D)()+a.A;
z5(a,a.A)},z5=function(a,b){if(null!=a.Wh)throw Error("WatchDog timer not null");
a.Wh=A5((0,g.A)(a.sJ,a),b)},B5=function(a){a.Wh&&(g.x.clearTimeout(a.Wh),a.Wh=null)},u5=function(a){a.g.Qr()||a.gg||a.g.Yk(a)},t5=function(a){B5(a);
g.Ve(a.ol);a.ol=null;a.l.stop();g.dp(a.aa);if(a.dc){var b=a.dc;a.dc=null;b.abort();b.dispose()}a.ce&&(a.ce=null)},s5=function(a,b){try{a.g.Av(a,b),a.g.Zd(4)}catch(c){}},D5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;C5(a,b,function(e){e?c(!0):g.x.setTimeout(function(){D5(a,b,c,d,f)},f)})}},C5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{E5(d),c(!0)}catch(e){}};
d.onerror=function(){try{E5(d),c(!1)}catch(e){}};
d.onabort=function(){try{E5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{E5(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},E5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},F5=function(a){this.g=a;
this.l=new j5},H5=function(a){var b=G5(a.g,a.ci,"/mail/images/cleardot.gif");
o4(b);D5(b.toString(),5E3,(0,g.A)(a.rz,a),3,2E3);a.Zd(1)},J5=function(a){var b=a.g.J;
if(null!=b)q5(5),b?(q5(11),I5(a.g,a,!1)):(q5(12),I5(a.g,a,!0));else if(a.rd=new k5(a,void 0,void 0,void 0),a.rd.qg=a.bn,b=a.g,b=G5(b,b.jj()?a.xi:null,a.cn),q5(5),!g.Gd||g.Cc(10))p4(b,"TYPE","xmlhttp"),n5(a.rd,b,!1,a.xi,!1);else{p4(b,"TYPE","html");var c=a.rd;a=!!a.xi;c.oh=3;c.yf=o4(b.clone());y5(c,a)}},K5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new j5;this.G=a||null;this.J=null!=b?b:null;this.C=c||!1},qka=function(a,b){this.g=a;
this.map=b;this.context=null},L5=function(a){g.Xe.call(this,"statevent",a)},M5=function(a,b){g.Xe.call(this,"timingevent",a);
this.size=b},N5=function(a){g.Xe.call(this,"serverreachability",a)},R5=function(a){O5(a);
if(3==a.g){var b=a.Vi++,c=a.fk.clone();g.Vo(c,"SID",a.o);g.Vo(c,"RID",b);g.Vo(c,"TYPE","terminate");P5(a,c);b=new k5(a,a.o,b,void 0);b.oh=2;b.yf=o4(c.clone());(new window.Image).src=b.yf;b.Lh=(0,g.D)();o5(b)}Q5(a)},T5=function(a){a.Ez(1,0);
a.fk=G5(a,null,a.an);S5(a)},O5=function(a){a.uf&&(a.uf.abort(),a.uf=null);
a.Kb&&(a.Kb.cancel(),a.Kb=null);a.Je&&(g.x.clearTimeout(a.Je),a.Je=null);U5(a);a.cd&&(a.cd.cancel(),a.cd=null);a.wf&&(g.x.clearTimeout(a.wf),a.wf=null)},V5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new qka(a.vF++,b));2!=a.g&&3!=a.g||S5(a)},S5=function(a){a.cd||a.wf||(a.wf=A5((0,g.A)(a.Ev,a),0),a.eh=0)},Y5=function(a,b){if(1==a.g){if(!b){a.Vi=Math.floor(1E5*Math.random());
var c=a.Vi++,d=new k5(a,"",c,void 0);d.qg=null;var e=W5(a),f=a.fk.clone();g.Vo(f,"RID",c);g.Vo(f,"CVER","1");P5(a,f);m5(d,f,e);a.cd=d;a.g=2}}else 3==a.g&&(b?X5(a,b):0==a.l.length||a.cd||X5(a))},X5=function(a,b){if(b)if(6<a.hg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Vi-1;var d=W5(a)}else c=b.F,d=b.Gg;else c=a.Vi++,d=W5(a);var e=a.fk.clone();g.Vo(e,"SID",a.o);g.Vo(e,"RID",c);g.Vo(e,"AID",a.vh);P5(a,e);c=new k5(a,a.o,c,a.eh+1);c.qg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.cd=c;m5(c,e,d)},P5=function(a,b){if(a.Ec){var c=a.Ec.Ar();
c&&g.Ub(c,function(a,c){g.Vo(b,c,a)})}},W5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.hg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.hg?e:f-d;try{g.Ub(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},Z5=function(a){a.Kb||a.Je||(a.F=1,a.Je=A5((0,g.A)(a.Dv,a),0),a.Vg=0)},a6=function(a){if(a.Kb||a.Je||3<=a.Vg)return!1;
a.F++;a.Je=A5((0,g.A)(a.Dv,a),$5(a,a.Vg));a.Vg++;return!0},I5=function(a,b,c){a.Pl=c;
a.ke=b.Te;a.C||T5(a)},U5=function(a){null!=a.jg&&(g.x.clearTimeout(a.jg),a.jg=null)},$5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},c6=function(a,b){if(2==b||9==b){var c=null;
a.Ec&&(c=null);var d=(0,g.A)(a.rK,a);c||(c=new g.Lo("//www.google.com/images/cleardot.gif"),o4(c));C5(c.toString(),1E4,d)}else q5(2);b6(a,b)},b6=function(a,b){a.g=0;
a.Ec&&a.Ec.Hq(b);Q5(a);O5(a)},Q5=function(a){a.g=0;
a.ke=-1;if(a.Ec)if(0==a.A.length&&0==a.l.length)a.Ec.zm();else{g.$a(a.A);var b=g.$a(a.l);a.A.length=0;a.l.length=0;a.Ec.zm(b)}},G5=function(a,b,c){var d=g.Wo(c);
if(""!=d.g)b&&g.No(d,b+"."+d.g),g.Oo(d,d.B);else{var e=window.location;d=Yja(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.ki&&g.Ub(a.ki,function(a,b){g.Vo(d,b,a)});
g.Vo(d,"VER",a.hg);P5(a,d);return d},A5=function(a,b){if(!g.Ca(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},q5=function(a){d6.dispatchEvent(new L5(d6,a))},e6=function(){},rka=function(a,b){this.action=a;
this.params=b||{}},f6=function(a,b){g.G.call(this);
this.g=new g.L(this.aJ,0,this);g.I(this,this.g);this.Fc=5E3;this.l=0;if(g.Ca(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ca(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},g6=function(a,b,c){this.L=a;
this.C=b;this.o=new g.Pq;this.l=new f6(this.SK,this);this.g=null;this.K=!1;this.B=null;this.J="";this.G=this.A=0;this.F=[];this.O=c||!1},ska=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Pl,sessionId:a.g.o,arrayId:a.g.vh}},h6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&Y5(a.g),R5(a.g));a.G=0},i6=function(a){return!!a.g&&3==a.g.g},tka=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},j6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Ug(a)||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Sb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Mb(a,"10.0")&&(this.l=!1))},k6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},l6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ja(a.A,d,!0),onError:g.Ja(a.o,e),Uc:g.Ja(a.B,e)};c&&(a.bb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.ps(b,a)},uka=function(){var a=m6;
n6();o6.push(a);p6(o6)},q6=function(a,b){n6();
var c=o6,d=vka(a,String(b));0==c.length?wka(d):(p6(c),(0,g.C)(c,function(a){a(d)}))},n6=function(){o6||(o6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",o6,void 0))},wka=function(a){var b=(r6+1)%50;
r6=b;s6[b]=a;t6||(t6=49==b)},p6=function(a){var b=s6;
if(b[0]){var c=r6,d=t6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
s6=Array(50);r6=-1;t6=!1}},vka=function(a,b){var c=((0,g.D)()-xka)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},u6=function(a){g.O.call(this);
this.F=a;this.g=[]},v6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},yka=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Wd)(a.g,function(a){return!!O4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=v6(a,b[d])||c;return c},zka=function(a,b){var c=a.g.length;
a.g=(0,g.Wd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},w6=function(a,b,c,d){g.O.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.ya=window.NaN},y6=function(a){u6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;x6(this);this.info("Initializing with "+M4(this.g))},z6=function(a){if(a.g.length){var b=(0,g.E)(a.g,function(a){return a.id}),c=k6(a.o,"/pairing/get_lounge_token_batch");
l6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.gA,a),(0,g.A)(a.fA,a))}},x6=function(a){var b=K4(W4());
b=(0,g.Wd)(b,function(a){return!a.uuid});
return yka(a,b)},A6=function(a,b){gka((0,g.E)(a.g,J4));
b&&X4()},C6=function(a,b){g.O.call(this);
this.C=b;var c=g.Vu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ta(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;B6("Initialized with "+g.Ig(this.g))},D6=function(a,b,c){var d=k6(a.B,"/pairing/get_screen_availability");
l6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},E6=function(a,b){a:if(g.Yb(b)!=g.Yb(a.g))var c=!1;
else{c=g.ac(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(B6("Updated online screens: "+g.Ig(a.g)),a.g=b,a.P("screenChange"));Aka(a)},F6=function(a){(0,window.isNaN)(a.o)||g.as(a.o);
a.o=g.Zr((0,g.A)(a.cp,a),0<a.A&&a.A<(0,g.D)()?2E4:1E4)},B6=function(a){q6("OnlineScreenService",a)},G6=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.Ab("Requesting availability of screen w/o lounge token.")});
return b},Aka=function(a){a=g.ac(g.Vb(a.g,function(a){return a}));
g.jb(a);a.length?g.Uu("yt-remote-online-screen-ids",a.join(","),60):g.Wu("yt-remote-online-screen-ids")},H6=function(a){u6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};Bka(this)},J6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.md();if(k=(c?P4(k,c):null)||P4(k,b)){k.uuid=b;var l=I6(a,k);D6(a.l,l,function(a){e(a?l:null)})}else c?Cka(a,c,(0,g.A)(function(a){var f=I6(this,new H4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));D6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},K6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Cka=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={bb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.ps(k6(a.C,"/pairing/get_lounge_token_batch"),e)},L6=function(a){a.g=a.o.md();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+M4(a.g))},Bka=function(a){M6(a);
a.o=new y6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.sA,a));L6(a);a.A=K4(g.Vu("yt-remote-automatic-screen-cache")||[]);M6(a);a.info("Initializing automatic screens: "+M4(a.A));a.l=new C6(a.C,(0,g.A)(a.md,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.P("onlineScreenChange")},a))},I6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=P4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Uu("yt-remote-automatic-screen-cache",(0,g.E)(a.A,J4)));M6(a);a.B[b.uuid]=b.id;g.Uu("yt-remote-device-id-map",a.B,31536E3);return b},M6=function(a){a.B=g.Vu("yt-remote-device-id-map")||{}},N6=function(a,b,c){g.O.call(this);
this.O=c;this.J=a;this.l=b;this.o=null},O6=function(a,b){q6(a.O,b)},Q6=function(a,b){N6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.YK,this);this.B=(0,g.A)(this.DJ,this);this.A=g.Zr((0,g.A)(function(){P6(this,null)},this),12E4)},Dka=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.xa,(0,g.A)(function(){O6(this,"Failed to send message: getMdxSessionStatus.")},a)):O6(a,"Sending yt message without session: "+g.Ig(b))},P6=function(a,b){g.as(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.Zk,a),d=(0,g.A)(a.qd,a);a.Kr(b,c,d,5)}}else a.qd(Error("Waiting for session status timed out."))},R6=function(a,b,c){N6.call(this,a,b,"DialSession");
this.A=this.G=null;this.K="";this.R=c;this.B=null;this.F=g.xa;this.C=window.NaN;this.L=(0,g.A)(this.bL,this);this.g=g.xa},S6=function(a){a.g=a.J.Mx(a.K,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.xa;
this.Zk(a)},a),(0,g.A)(function(a){this.g=g.xa;
this.qd(a)},a))},T6=function(a){var b={};
b.pairingCode=a.K;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}$4()&&(b.env_useStageMdx=1);return g.ah(b)},U6=function(a,b){N6.call(this,a,b,"ManualSession");
this.g=g.Zr((0,g.A)(this.wh,this,null),150)},V6=function(a,b,c,d){g.O.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.lI,this)},W6=function(a,b){return b?g.Pa(a.o,function(a){return I4(b,a.label)},a):null},X6=function(a){q6("Controller",a)},m6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},Y6=function(a){return a.B||!!a.o.length||!!a.g},Z6=function(a,b,c){b!=a.g&&(g.Ve(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.Cv,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.wh(null)):a.P("yt-remote-cast2-session-change",null))},$6=function(a){var b=a.l.Lx(),c=a.g&&a.g.l;
a=(0,g.E)(b,function(a){c&&I4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=W6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Hka=function(a,b,c,d,e,f,k){Eka()?Fka(b,e,f,k)&&(b7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?c7(a,c):(window.__onGCastApiAvailable=function(b,d){b?c7(a,c):(d7("Failed to load cast API: "+d),e7(!1),b7(!1),g.Wu("yt-remote-cast-available"),g.Wu("yt-remote-cast-receiver"),f7(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):kka():g5("CriOS")?nka():g5("Android")&&g5("Chrome/")&&window.navigator.presentation?oka():window.chrome&&window.navigator.presentation&&!g5("Edge")?(h5(),d5(Gka.map(lka))):e5())):a7("Cannot initialize because not running Chrome")},f7=function(){a7("dispose");
var a=g7();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);h7(!1);g.au(i7);i7.length=0},j7=function(){return!!g.Vu("yt-remote-cast-installed")},k7=function(){var a=g.Vu("yt-remote-cast-receiver");
return a?a.friendlyName:null},l7=function(){a7("clearCurrentReceiver");
g.Wu("yt-remote-cast-receiver")},m7=function(){return j7()?g7()?g7().getCastSession():(d7("getCastSelector: Cast is not initialized."),null):(d7("getCastSelector: Cast API is not installed!"),null)},o7=function(){j7()?g7()?n7()?(a7("Requesting cast selector."),g7().requestSession()):(a7("Wait for cast API to be ready to request the session."),i7.push(g.$t("yt-remote-cast2-api-ready",o7))):d7("requestCastSelector: Cast is not initialized."):d7("requestCastSelector: Cast API is not installed!")},p7=
function(a,b){n7()?g7().setConnectedScreenStatus(a,b):d7("setConnectedScreenStatus called before ready.")},Eka=function(){var a=0<=g.Sb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Jw||a},Ika=function(a,b){g7().init(a,b)},Fka=function(a,b,c,d){var e=!1;
g7()||(a=new V6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Uu("yt-remote-cast-available",a);g.du("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){a7("onReceiverSelected: "+a.friendlyName);
g.Uu("yt-remote-cast-receiver",a);g.du("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){a7("onReceiverResumed: "+a.friendlyName);
g.Uu("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){a7("onSessionChange: "+L4(a));
a||g.Wu("yt-remote-cast-receiver");g.du("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
a7("cloudview.createSingleton_: "+e);return e},g7=function(){return g.z("yt.mdx.remote.cloudview.instance_")},c7=function(a,b){e7(!0);
b7(!1);Ika(a,function(a){a?(h7(!0),g.cu("yt-remote-cast2-api-ready")):(d7("Failed to initialize cast API."),e7(!1),g.Wu("yt-remote-cast-available"),g.Wu("yt-remote-cast-receiver"),f7());b(a)})},a7=function(a){q6("cloudview",a)},d7=function(a){q6("cloudview",a)},e7=function(a){a7("setCastInstalled_ "+a);
g.Uu("yt-remote-cast-installed",a)},n7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},h7=function(a){a7("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},b7=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},q7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.l=null;this.hasNext=this.ne=!1;this.K=this.J=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},r7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.ne=!1;a.hasNext=!1;a.G=0;a.F=(0,g.D)();a.B=0;a.o=0;a.J=0;a.K=0;a.A=window.NaN;a.C=!1},s7=function(a){return 1==a.g?((0,g.D)()-a.F)/1E3:0},t7=function(a,b){a.G=b;
a.F=(0,g.D)()},u7=function(a){switch(a.g){case 1:case 1081:return((0,g.D)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},v7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&r7(a)},w7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.mc(a.l);b.hasPrevious=a.ne;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.A;return b},z7=function(a,b){g.O.call(this);
this.g=0;this.A=a;this.C=[];this.B=new E4;this.o=this.l=null;this.J=(0,g.A)(this.dG,this);this.F=(0,g.A)(this.Yi,this);this.G=(0,g.A)(this.cG,this);this.K=(0,g.A)(this.pG,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Hp,this),x7(this))):c=3;0!=c&&(b?this.Hp(c):g.Zr((0,g.A)(function(){this.Hp(c)},this),0));
var d=m7();d&&y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},A7=function(a){return new q7(a.A.getPlayerContextData())},x7=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ja(this.hI,a),this))},a)},B7=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},E7=function(a,b,c){var d=A7(a);
t7(d,c);-1E3!=d.g&&(d.g=b);D7(a,d)},F7=function(a,b,c){a.A.sendMessage(b,c)},D7=function(a,b){B7(a);
a.A.setPlayerContextData(w7(b));x7(a)},y7=function(a,b){a.o&&(a.o.removeUpdateListener(a.J),a.o.removeMediaListener(a.F),a.Yi(null));
a.o=b;a.o&&(q6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.J),a.o.addMediaListener(a.F),a.o.media.length&&a.Yi(a.o.media[0]))},G7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=A7(a);b.contentId!=d.videoId&&q6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;t7(d,a.l.getEstimatedTime());D7(a,d)}else q6("CP","No cast media video. Ignoring state update.")},H7=function(a,b,c){return(0,g.A)(function(a){this.Ab("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Ab("Retrying "+b+" using MDx browser channel."),F7(this,b,c))},a)},I7=function(a,b,c){g.O.call(this);
this.B=window.NaN;this.R=!1;this.K=this.J=this.L=this.O=window.NaN;this.T=[];this.A=this.F=this.o=this.Ja=this.g=null;this.ra=a;this.T.push(g.zt(window,"beforeunload",(0,g.A)(this.Zz,this)));this.l=[];this.Ja=new q7;this.X=b.id;this.g=Jka(this,c);this.g.subscribe("handlerOpened",this.hG,this);this.g.subscribe("handlerClosed",this.eG,this);this.g.subscribe("handlerError",this.fG,this);this.g.subscribe("handlerMessage",this.gG,this);tka(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Ja.videoId;g.Xu()&&g.Uu("yt-remote-session-video-id",a)},this)},J7=function(a){q6("conn",a)},Jka=function(a,b){return new g6(k6(a.ra,"/bc"),b)},K7=function(a,b){a.P("proxyStateChange",b)},Kka=function(a){a.B=g.Zr((0,g.A)(function(){J7("Connecting timeout");
this.C(1)},a),2E4)},L7=function(a){g.as(a.B);
a.B=window.NaN},M7=function(a){g.as(a.O);
a.O=window.NaN},Lka=function(a){N7(a);
a.L=g.Zr((0,g.A)(function(){O7(this,"getNowPlaying")},a),2E4)},N7=function(a){g.as(a.L);
a.L=window.NaN},Q7=function(a,b){b&&(L7(a),M7(a));
b==(i6(a.g)&&(0,window.isNaN)(a.B))?b&&(K7(a,1),O7(a,"getSubtitlesTrack")):b?(a.Y()&&a.Ja.reset(),K7(a,1),O7(a,"getNowPlaying"),P7(a)):a.C(1)},Mka=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ja.videoId&&(g.gc(b.params)?a.Ja.l=null:a.Ja.l=b.params,a.P("remotePlayerChange"))},R7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Ja.listId=b.params.listId||a.Ja.listId;v7(a.Ja,c,d);a.P("remoteQueueChange")},Nka=function(a,b){b.params=b.params||{};
R7(a,b);S7(a,b);a.P("autoplayDismissed")},S7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
t7(a.Ja,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Ja.g&&(c=-1E3);a.Ja.g=c;c=Number(b.params.loadedTime);a.Ja.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Ja.J=(0,window.isNaN)(c)?0:c;c=a.Ja;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Ja;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Ja.g?Lka(a):N7(a);
a.P("remotePlayerChange")},Oka=function(a,b){if(-1E3!=a.Ja.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ja.g=c;c=(0,window.parseInt)(b.params.currentTime,10);t7(a.Ja,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},Pka=function(a,b){var c="true"==b.params.muted;
a.Ja.volume=(0,window.parseInt)(b.params.volume,10);a.Ja.muted=c;a.P("remotePlayerChange")},Qka=function(a,b){a.F=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Rka=function(a,b){var c="true"==b.params.hasNext;
a.Ja.ne="true"==b.params.hasPrevious;a.Ja.hasNext=c;a.P("previousNextChange")},P7=function(a){g.as(a.K);
a.K=g.Zr((0,g.A)(a.C,a,1),864E5)},O7=function(a,b,c){c?J7("Sending: action="+b+", params="+g.Ig(c)):J7("Sending: action="+b);
a.g.sendMessage(b,c)},T7=function(a){u6.call(this,"ScreenServiceProxy");
this.xc=a;this.l=[];this.l.push(this.xc.$_s("screenChange",(0,g.A)(this.WK,this)));this.l.push(this.xc.$_s("onlineScreenChange",(0,g.A)(this.OH,this)))},Wka=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Sr("MDX_CONFIG")||b;eka();U4();U7||(U7=new j6(b?b.loungeApiHost:void 0),$4()&&(U7.g="/api/loungedev"));V7||(V7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",V7,void 0));Ska();var c=W7();if(!c){var d=new H6(U7);g.y("yt.mdx.remote.screenService_",d,void 0);c=W7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Hka(a,d,function(a){a?X7()&&p7(X7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.du("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),Y7("Initializing: "+g.Ig(b)),Z7.push(g.$t("yt-remote-cast2-availability-change",function(){g.du("yt-remote-receiver-availability-change")})),Z7.push(g.$t("yt-remote-cast2-receiver-selected",function(){$7(null);
g.du("yt-remote-auto-connect","cast-selector-receiver")})),Z7.push(g.$t("yt-remote-cast2-receiver-resumed",function(){g.du("yt-remote-receiver-resumed","cast-selector-receiver")})),Z7.push(g.$t("yt-remote-cast2-session-change",Tka)),Z7.push(g.$t("yt-remote-connection-change",function(a){a?p7(X7(),"YouTube TV"):a8()||(p7(null,null),l7())})),a=b8(),b.isAuto&&(a.id+="#dial"),g.Ut("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),Y7(" -- with channel params: "+
g.Ig(a)),Uka(a),c.start(),X7()||Vka())},Xka=function(){var a=c8();
j7()&&g.Vu("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},c8=function(){var a=W7().xc.$_gos();
var b=d8();b&&e8()&&(O4(a,b)||a.push(b));return dka(a)},f8=function(){var a=Yka();
!a&&j7()&&k7()&&(a={key:"cast-selector-receiver",name:k7()});return a},Yka=function(){var a=c8(),b=d8();
b||(b=a8());return g.Pa(a,function(a){return b&&I4(b,a.key)?!0:!1})},d8=function(){var a=X7();
if(!a)return null;var b=W7().md();return P4(b,a)},Tka=function(a){Y7("remote.onCastSessionChange_: "+L4(a));
if(a){var b=d8();b&&b.id==a.id?p7(b.id,"YouTube TV"):(b&&g8(),h8(a,1))}else e8()&&g8()},g8=function(){n7()?g7().stopSession():d7("stopSession called before API ready.");
var a=e8();a&&(a.disconnect(1),i8(null))},j8=function(){var a=e8();
return!!a&&3!=a.getProxyState()},Y7=function(a){q6("remote",a)},W7=function(){if(!k8){var a=g.z("yt.mdx.remote.screenService_");
k8=a?new T7(a):null}return k8},X7=function(){return g.z("yt.mdx.remote.currentScreenId_")},l8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},m8=function(){return g.z("yt.mdx.remote.connectData_")},$7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},e8=function(){return g.z("yt.mdx.remote.connection_")},i8=function(a){var b=e8();
$7(null);a||l8("");g.y("yt.mdx.remote.connection_",a,void 0);V7&&((0,g.C)(V7,function(b){b(a)}),V7.length=0);
b&&!a?g.du("yt-remote-connection-change",!1):!b&&a&&g.du("yt-remote-connection-change",!0)},a8=function(){var a=g.Xu();
if(!a)return null;var b=W7().md();return P4(b,a)},h8=function(a,b){d8()&&d8();
l8(a.id);var c=new I7(U7,a,b8());c.connect(b,m8());c.subscribe("beforeDisconnect",function(a){g.du("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){e8()&&i8(null)});
i8(c)},Vka=function(){var a=a8();
a?(Y7("Resume connection to: "+L4(a)),h8(a,0)):(Y4(),l7(),Y7("Skipping connecting because no session screen found."))},Ska=function(){var a=b8();
if(g.gc(a)){a=T4();var b=g.Vu("yt-remote-session-name")||"",c=g.Vu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},b8=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Uka=function(a){a?(g.Uu("yt-remote-session-app",a.app),g.Uu("yt-remote-session-name",a.name)):(g.Wu("yt-remote-session-app"),g.Wu("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},n8=function(a,b,c){g.G.call(this);
this.G=a;this.l=b;this.o=new g.Mt(this);g.I(this,this.o);this.o.M(b,"onCaptionsTrackListChanged",this.hH);this.o.M(b,"captionschanged",this.bG);this.o.M(b,"captionssettingschanged",this.Vw);this.o.M(b,"videoplayerreset",this.al);this.o.M(b,"mdxautoplaycancel",this.qz);this.T=this.o.M(b,"onVolumeChange",this.ov);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.zv,this);c.subscribe("remotePlayerChange",this.Zi,this);c.subscribe("remoteQueueChange",this.al,this);c.subscribe("autoplayUpNext",this.Wu,
this);c.subscribe("previousNextChange",this.wv,this);c.subscribe("nowAutoplaying",this.rv,this);c.subscribe("autoplayDismissed",this.Vu,this);this.suggestion=null;this.J=new g.QD(64);this.A=new g.L(this.Sw,500,this);g.I(this,this.A);this.B=new g.L(this.Tw,1E3,this);g.I(this,this.B);this.L=new i5(this.DK,0,this);g.I(this,this.L);this.C={};this.O=new g.L(this.zx,1E3,this);g.I(this,this.O);this.K=new g.Am(this.QD,1E3,this);g.I(this,this.K);this.R=g.xa;this.Vw();this.al();this.Zi()},o8=function(a,b){var c=
a.G,d=a.l.getVideoData().lengthSeconds;
c.J=b||0;c.g.P("progresssync",b,d)},q8=function(a){o8(a,0);
a.A.stop();p8(a,new g.QD(64))},s8=function(a,b){if(r8(a)&&!a.F){var c=null;
b&&(c={style:a.l.Cg()},g.oc(c,b));a.g.Jw(a.l.getVideoData(1).videoId,c);a.C=A7(a.g).l}},t8=function(a,b){var c=a.l.xe();
if(c){var d=c.Ma;var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.rh;f=D4(f);var n=A7(c);l=l||0;var q={videoId:k,currentIndex:l};v7(n,k,l);g.t(b)&&(t7(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Ig(f));F7(c,"setPlaylist",q);e||D7(c,n);p8(a,new g.QD(1))},u8=function(a,b){if(b){var c=a.l.Nb("captions","tracklist",{us:1});
c&&c.length?(a.l.Sc("captions","track",b),a.F=!1):(a.l.zh("captions"),a.F=!0)}else a.l.Sc("captions","track",{})},r8=function(a){return A7(a.g).videoId==a.l.getVideoData(1).videoId},p8=function(a,b){a.B.stop();
var c=a.J;if(!g.VD(c,b)){var d=g.U(b,2);d!=g.U(a.J,2)&&g.oK(a.l,d);a.J=b;v8(a.G,c,b)}},x8=function(a){g.R.call(this,{D:"div",
I:"ytp-remote",H:[{D:"div",I:"ytp-remote-display-status",H:[{D:"div",I:"ytp-remote-display-status-icon",H:[g.xO()]},{D:"div",I:"ytp-remote-display-status-text",H:["{{statustext}}"]}]}]});this.l=new g.hP(this,250);g.I(this,this.l);this.o=a;this.M(a,"presentingplayerstatechange",this.A);w8(this,g.lK(a))},w8=function(a,b){if(3==a.o.Da()){var c={RECEIVER_NAME:a.o.Nb("remote","currentReceiver").name};
c=g.U(b,128)?g.Q("YTP_MDX_STATUS_ERROR_2",c):g.WD(b)||g.U(b,4)?g.Q("YTP_MDX_STATUS_PLAYING_2",c):g.Q("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},y8=function(a,b){g.NT.call(this,g.Q("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.G={};this.M(a,"onMdxReceiversChange",this.K);this.M(a,"presentingplayerstatechange",this.K);this.K()},z8=function(a){g.RK.call(this,a);
g.Zu({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:N4(),name:g.Q("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.K=this.l=null;this.G=[this.o];this.A=this.o;this.F=new g.QD(64);this.J=0;if(!g.gB(g.V(this.g))){a=
this.g;var b=g.Mv(a);b&&(b=b.Fk())&&(b=new y8(a,b),g.I(this,b));b=new x8(a);g.I(this,b);g.GK(a,b.element,4)}},v8=function(a,b,c){a.F=c;
a.g.P("presentingplayerstatechange",new g.aE(c,b))},A8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)g8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.xe();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.sb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.rh,index:Math.max(a.g.Dt(),0),currentTime:0==f?void 0:f};(d=D4(d))&&(c.locationInfo=d);d=c}else d=null;Y7("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?($7(d||null),n7()?g7().setLaunchParams(d||null):
d7("setLaunchParams called before ready.")):!d&&j8()&&X7()==b.key?g.du("yt-remote-connection-change",!0):(g8(),$7(d||null),d=W7().md(),(d=P4(d,b.key))&&h8(d,1))}},Vja=/^https?$/i,Zka=["POST",
"PUT"];g.B(B4,g.Af);g.h=B4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.J+"; newUri="+a);b=b?b.toUpperCase():"GET";this.J=a;this.B="";this.A=0;this.W=b;this.T=!1;this.l=!0;this.g=this.R?t4(this.R):t4(g.WW);this.O=this.R?s4(this.R):s4(g.WW);this.g.onreadystatechange=(0,g.A)(this.Sr,this);try{q4(u4(this,"Opening Xhr")),this.X=!0,this.g.open(b,String(a),!0),this.X=!1}catch(f){q4(u4(this,"Error opening Xhr: "+f.message));y4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Sja(d,function(a,b){e.set(b,a)});
d=g.Pa(e.kd(),Tja);c=g.x.FormData&&a instanceof g.x.FormData;!g.Ta(Zka,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.ca&&(this.g.responseType=this.ca);"withCredentials"in this.g&&this.g.withCredentials!==this.Y&&(this.g.withCredentials=this.Y);try{v4(this),0<this.C&&(this.L=Uja(this.g),q4(u4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.L)),this.L?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.Tr,this)):this.F=g.yg(this.Tr,this.C,this)),q4(u4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){q4(u4(this,"Send error: "+f.message)),y4(this,f)}};
g.h.Tr=function(){"undefined"!=typeof g.yW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,u4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(u4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),x4(this))};
g.h.U=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),x4(this,!0));B4.ua.U.call(this)};
g.h.Sr=function(){this.fa()||(this.X||this.G||this.o?A4(this):this.kI())};
g.h.kI=function(){A4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<z4(this)?this.g.status:-1}catch(a){return-1}};
var x5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},w5={"'":"\\'"},$ka={};g.h=E4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Ta(this.g,a)||g.Ta(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Pfa)(b,a);0<=c?(g.Wa(b,c),b=!0):b=!1;return b||g.Xa(this.l,a)};
g.h.hc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var bka={lL:"atp",wN:"ska",lN:"que",LM:"mus",vN:"sus",bM:"dsp"};G4.prototype.Qj=function(){var a=new G4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var Z4,S4="",f5=a5("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",mka=a5("loadCastFramework")||a5("loadCastApplicationFramework"),Gka=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(i5,g.G);g.h=i5.prototype;g.h.Uz=function(a){this.A=arguments;this.g=!1;this.ya?this.o=(0,g.D)()+this.Fc:this.ya=g.yg(this.B,this.Fc)};
g.h.stop=function(){this.ya&&(g.x.clearTimeout(this.ya),this.ya=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();i5.ua.U.call(this)};
g.h.Vz=function(){this.o?(this.ya=g.yg(this.B,this.o-(0,g.D)()),this.o=null):(this.ya=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};j5.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
j5.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=k5.prototype;g.h.qg=null;g.h.be=!1;g.h.Wh=null;g.h.Fp=null;g.h.Lh=null;g.h.oh=null;g.h.yf=null;g.h.Rf=null;g.h.Gg=null;g.h.dc=null;g.h.rj=0;g.h.ce=null;g.h.Ql=null;g.h.zf=null;g.h.yi=-1;g.h.uw=!0;g.h.gg=!1;g.h.dn=0;g.h.ol=null;var r5={},p5={};g.h=k5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.NJ=function(a){a=a.target;var b=this.ol;b&&3==z4(a)?b.mh():this.Fx(a)};
g.h.Fx=function(a){try{if(a==this.dc)a:{var b=z4(this.dc),c=this.dc.A,d=this.dc.getStatus();if(g.Gd&&!g.Cc(10)||g.Id&&!g.Ac("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ih&&!C4(this.dc))break a;this.gg||4!=b||7==c||(8==c||0>=d?this.g.Zd(3):this.g.Zd(2));B5(this);var e=this.dc.getStatus();this.yi=e;var f=C4(this.dc);(this.be=200==e)?(4==b&&t5(this),this.B?(v5(this,b,f),g.Ih&&this.be&&3==b&&(this.aa.da(this.l,"tick",this.JJ),this.l.start())):s5(this,f),this.be&&!this.gg&&(4==b?this.g.Yk(this):(this.be=
!1,o5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.zf=3,q5(13)):(this.zf=0,q5(14)),t5(this),u5(this))}}catch(k){this.dc&&C4(this.dc)}finally{}};
g.h.JJ=function(){var a=z4(this.dc),b=C4(this.dc);this.rj<b.length&&(B5(this),v5(this,a,b),this.be&&4!=a&&o5(this))};
g.h.hJ=function(a){A5((0,g.A)(this.gJ,this,a),0)};
g.h.gJ=function(a){this.gg||(B5(this),s5(this,a),o5(this))};
g.h.Gv=function(a){A5((0,g.A)(this.fJ,this,a),0)};
g.h.fJ=function(a){this.gg||(t5(this),this.be=a,this.g.Yk(this),this.g.Zd(4))};
g.h.cancel=function(){this.gg=!0;t5(this)};
g.h.sJ=function(){this.Wh=null;var a=(0,g.D)();0<=a-this.Fp?(2!=this.oh&&this.g.Zd(3),t5(this),this.zf=2,q5(18),u5(this)):z5(this,this.Fp-a)};g.h=F5.prototype;g.h.bn=null;g.h.rd=null;g.h.pl=!1;g.h.Rr=null;g.h.bk=null;g.h.Hn=null;g.h.cn=null;g.h.Dd=null;g.h.Te=-1;g.h.xi=null;g.h.ci=null;g.h.connect=function(a){this.cn=a;a=G5(this.g,null,this.cn);q5(3);this.Rr=(0,g.D)();var b=this.g.G;null!=b?(this.xi=b[0],(this.ci=b[1])?(this.Dd=1,H5(this)):(this.Dd=2,J5(this))):(p4(a,"MODE","init"),this.rd=new k5(this,void 0,void 0,void 0),this.rd.qg=this.bn,n5(this.rd,a,!1,null,!0),this.Dd=0)};
g.h.rz=function(a){if(a)this.Dd=2,J5(this);else{q5(4);var b=this.g;b.ke=b.uf.Te;c6(b,9)}a&&this.Zd(2)};
g.h.Hm=function(a){return this.g.Hm(a)};
g.h.abort=function(){this.rd&&(this.rd.cancel(),this.rd=null);this.Te=-1};
g.h.Qr=function(){return!1};
g.h.Av=function(a,b){this.Te=a.yi;if(0==this.Dd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.ke=this.Te;c6(c,2);return}this.xi=c[0];this.ci=c[1]}else c=this.g,c.ke=this.Te,c6(c,2);else if(2==this.Dd)if(this.pl)q5(7),this.Hn=(0,g.D)();else if("11111"==b){if(q5(6),this.pl=!0,this.bk=(0,g.D)(),c=this.bk-this.Rr,!g.Gd||g.Cc(10)||500>c)this.Te=200,this.rd.cancel(),q5(12),I5(this.g,this,!0)}else q5(8),this.bk=this.Hn=(0,g.D)(),this.pl=!1};
g.h.Yk=function(){this.Te=this.rd.yi;if(this.rd.be)0==this.Dd?this.ci?(this.Dd=1,H5(this)):(this.Dd=2,J5(this)):2==this.Dd&&((!g.Gd||g.Cc(10)?!this.pl:200>this.Hn-this.bk)?(q5(11),I5(this.g,this,!1)):(q5(12),I5(this.g,this,!0)));else{0==this.Dd?q5(9):2==this.Dd&&q5(10);var a=this.g;a.ke=this.Te;c6(a,2)}};
g.h.jj=function(){return this.g.jj()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Zd=function(a){this.g.Zd(a)};g.h=K5.prototype;g.h.ki=null;g.h.cd=null;g.h.Kb=null;g.h.an=null;g.h.fk=null;g.h.Aq=null;g.h.lk=null;g.h.Vi=0;g.h.vF=0;g.h.Ec=null;g.h.wf=null;g.h.Je=null;g.h.jg=null;g.h.uf=null;g.h.Pl=null;g.h.vh=-1;g.h.Ns=-1;g.h.ke=-1;g.h.eh=0;g.h.Vg=0;g.h.hg=8;var d6=new g.Af;g.B(L5,g.Xe);g.B(M5,g.Xe);g.B(N5,g.Xe);g.h=K5.prototype;g.h.connect=function(a,b,c,d,e){q5(0);this.an=b;this.ki=c||{};d&&g.t(e)&&(this.ki.OSID=d,this.ki.OAID=e);this.C?(A5((0,g.A)(this.Uq,this,a),100),T5(this)):this.Uq(a)};
g.h.Uq=function(a){this.uf=new F5(this);this.uf.bn=null;this.uf.l=this.B;this.uf.connect(a)};
g.h.Qr=function(){return 0==this.g};
g.h.Ev=function(a){this.wf=null;Y5(this,a)};
g.h.Dv=function(){this.Je=null;this.Kb=new k5(this,this.o,"rpc",this.F);this.Kb.qg=null;this.Kb.dn=0;var a=this.Aq.clone();g.Vo(a,"RID","rpc");g.Vo(a,"SID",this.o);g.Vo(a,"CI",this.Pl?"0":"1");g.Vo(a,"AID",this.vh);P5(this,a);if(!g.Gd||g.Cc(10))g.Vo(a,"TYPE","xmlhttp"),n5(this.Kb,a,!0,this.lk,!1);else{g.Vo(a,"TYPE","html");var b=this.Kb,c=!!this.lk;b.oh=3;b.yf=o4(a.clone());y5(b,c)}};
g.h.Av=function(a,b){if(0!=this.g&&(this.Kb==a||this.cd==a))if(this.ke=a.yi,this.cd==a&&3==this.g)if(7<this.hg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Aa(c)&&3==c.length)if(0==c[0])a:{if(!this.Je){if(this.Kb)if(this.Kb.Lh+3E3<this.cd.Lh)U5(this),this.Kb.cancel(),this.Kb=null;else break a;a6(this);q5(19)}}else this.Ns=c[1],0<this.Ns-this.vh&&37500>c[2]&&this.Pl&&0==this.Vg&&!this.jg&&(this.jg=A5((0,g.A)(this.XF,this),6E3));else c6(this,11)}else b!=$ka.LL.g&&c6(this,11);else if(this.Kb==a&&
U5(this),!g.tb(b)){c=this.B.parse(b);g.Aa(c);for(var d=0;d<c.length;d++){var e=c[d];this.vh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.lk=e[2],e=e[3],null!=e?this.hg=e:this.hg=6,this.g=3,this.Ec&&this.Ec.Jq(),this.Aq=G5(this,this.jj()?this.lk:null,this.an),Z5(this)):"stop"==e[0]&&c6(this,7):3==this.g&&("stop"==e[0]?c6(this,7):"noop"!=e[0]&&this.Ec&&this.Ec.Iq(e),this.Vg=0)}}};
g.h.XF=function(){null!=this.jg&&(this.jg=null,this.Kb.cancel(),this.Kb=null,a6(this),q5(20))};
g.h.Yk=function(a){if(this.Kb==a){U5(this);this.Kb=null;var b=2}else if(this.cd==a)this.cd=null,b=1;else return;this.ke=a.yi;if(0!=this.g)if(a.be)1==b?(b=(0,g.D)()-a.Lh,d6.dispatchEvent(new M5(d6,a.Gg?a.Gg.length:0,b,this.eh)),S5(this),this.A.length=0):Z5(this);else{var c=a.zf,d;if(!(d=3==c||7==c||0==c&&0<this.ke)){if(d=1==b)this.cd||this.wf||1==this.g||2<=this.eh?d=!1:(this.wf=A5((0,g.A)(this.Ev,this,a),$5(this,this.eh)),this.eh++,d=!0);d=!(d||2==b&&a6(this))}if(d)switch(c){case 1:c6(this,5);break;
case 4:c6(this,10);break;case 3:c6(this,6);break;case 7:c6(this,12);break;default:c6(this,2)}}};
g.h.Ez=function(a){if(!g.Ta(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.rK=function(a){a?q5(2):(q5(1),b6(this,8))};
g.h.Hm=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new B4;a.Y=!1;return a};
g.h.isActive=function(){return!!this.Ec&&this.Ec.isActive(this)};
g.h.Zd=function(a){d6.dispatchEvent(new N5(d6,a))};
g.h.jj=function(){return!(!g.Gd||g.Cc(10))};
g.h=e6.prototype;g.h.Jq=function(){};
g.h.Iq=function(){};
g.h.Hq=function(){};
g.h.zm=function(){};
g.h.Ar=function(){return{}};
g.h.isActive=function(){return!0};g.B(f6,g.G);g.h=f6.prototype;g.h.aJ=function(){this.Fc=Math.min(3E5,2*this.Fc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Fc+15E3*Math.random();g.wq(this.g,a);this.l=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Fc=5E3};g.B(g6,e6);g.h=g6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Bc=function(a){return this.o.Bc(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.Ve(this.o),h6(this),g.Ve(this.l),this.l=null)};
g.h.fa=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.J="";this.l.stop();this.B=a||null;this.A=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new K5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.O),e=this.g;e&&(e.Ec=null);d.Ec=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.vh):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.oc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):i6(this)&&V5(this.g,c)};
g.h.Jq=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)V5(this.g,a[b])}this.P("handlerOpened")};
g.h.Hq=function(a){var b=2==a&&401==this.g.ke;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.zm=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Ar=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.oc(a,this.B);return a};
g.h.Iq=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),R5(this.g)):this.P("handlerMessage",new rka(a[0],a[1]))};
g.h.SK=function(){this.l.isActive();var a=this.g,b=0;a.Kb&&b++;a.cd&&b++;0!=b||this.connect(this.B,this.A)};j6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
j6.prototype.B=function(a){a(Error("request timed out"))};var xka=(0,g.D)(),o6=null,s6=Array(50),r6=-1,t6=!1;g.B(u6,g.O);u6.prototype.md=function(){return this.g};
u6.prototype.contains=function(a){return!!O4(this.g,a)};
u6.prototype.get=function(a){return a?P4(this.g,a):null};
u6.prototype.info=function(a){q6(this.F,a)};g.B(w6,g.O);var B8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=w6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.ya)&&this.Kx()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.ya)||(g.as(this.ya),this.ya=window.NaN)};
g.h.U=function(){this.stop();w6.ua.U.call(this)};
g.h.Kx=function(){this.ya=window.NaN;this.g=g.ps(k6(this.C,"/pairing/get_screen"),{method:"POST",bb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.UK,this),onError:(0,g.A)(this.TK,this),Uc:(0,g.A)(this.VK,this)})};
g.h.UK=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new H4(c))};
g.h.TK=function(a){this.g=null;a.status&&404==a.status?this.l>=B8.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=B8[this.l],this.ya=g.Zr((0,g.A)(this.Kx,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.VK=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.B(y6,u6);g.h=y6.prototype;g.h.start=function(){x6(this)&&this.P("screenChange");!g.Vu("yt-remote-lounge-token-expiration")&&z6(this);g.as(this.l);this.l=g.Zr((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){x6(this);v6(this,a);A6(this,!1);this.P("screenChange");b(a);a.token||z6(this)};
g.h.remove=function(a,b){var c=x6(this);zka(this,a)&&(A6(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Kl=function(a,b,c,d){var e=x6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,A6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.as(this.l);y6.ua.U.call(this)};
g.h.gA=function(a){x6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}A6(this,!b);b&&q6(this.F,"Missed "+b+" lounge tokens.")};
g.h.fA=function(a){q6(this.F,"Requesting lounge tokens failed: "+a)};g.B(C6,g.O);g.h=C6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.Vu("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.D)()-144E5<a?0:a)?F6(this):(this.A=(0,g.D)()+3E5,g.Uu("yt-remote-fast-check-period",this.A),this.cp())};
g.h.isEmpty=function(){return g.gc(this.g)};
g.h.update=function(){B6("Updating availability on schedule.");var a=this.C(),b=g.Vb(this.g,function(b,d){return b&&!!P4(a,d)},this);
E6(this,b)};
g.h.U=function(){g.as(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);C6.ua.U.call(this)};
g.h.cp=function(){g.as(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=G6(this);if(g.Yb(a)){var b=k6(this.B,"/pairing/get_screen_availability");this.l=l6(this.B,b,{lounge_token:g.ac(a).join(",")},(0,g.A)(this.FI,this,a),(0,g.A)(this.DI,this))}else E6(this,{}),F6(this)};
g.h.FI=function(a,b){this.l=null;var c=g.ac(G6(this));if(g.nb(c,g.ac(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;E6(this,d);F6(this)}else this.Ab("Changing Screen set during request."),this.cp()};
g.h.DI=function(a){this.Ab("Screen availability failed: "+a);this.l=null;F6(this)};
g.h.Ab=function(a){q6("OnlineScreenService",a)};g.B(H6,u6);g.h=H6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Kl=function(a,b,c,d){this.o.contains(a)?this.o.Kl(a,b,c,d):(a="Updating name of unknown screen: "+a.name,q6(this.F,a),d(Error(a)))};
g.h.md=function(a){return a?this.g:g.Za(this.g,(0,g.Wd)(this.A,function(a){return!this.contains(a)},this))};
g.h.Lx=function(){return(0,g.Wd)(this.md(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.Mx=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new w6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ve(f);d(I6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ve(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.XK=function(a,b,c,d){g.ps(k6(this.C,"/pairing/get_screen"),{method:"POST",bb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new H4(d.screen||{});if(!e.name||K6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);K6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(I6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Uc:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Ve(this.o);g.Ve(this.l);H6.ua.U.call(this)};
g.h.sA=function(){L6(this);this.P("screenChange");this.l.update()};
H6.prototype.dispose=H6.prototype.dispose;g.B(N6,g.O);g.h=N6.prototype;g.h.Zk=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.qd=function(a){this.fa()||(a&&O6(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){q6(this.O,a)};
g.h.Ox=function(){return null};
g.h.jp=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){O6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.jp("");N6.ua.U.call(this)};g.B(Q6,N6);g.h=Q6.prototype;g.h.ip=function(a){if(this.g){if(this.g==a)return;O6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Dka(this)};
g.h.wh=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.qd()},this),(0,g.A)(function(){this.qd(Error("Failed to stop receiver app."))},this)):this.qd(Error("Stopping cast device witout session."))};
g.h.jp=g.xa;g.h.U=function(){this.info("disposeInternal");g.as(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;Q6.ua.U.call(this)};
g.h.DJ=function(a,b){if(!this.fa())if(b){var c=g.Hq(b);if(g.Da(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":P6(this,c.screenId);break;default:O6(this,"Unknown youtube message: "+d)}}else O6(this,"Unable to parse message.")}else O6(this,"No data in message.")};
g.h.Kr=function(a,b,c,d){J6(this.J,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(O6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Zr((0,g.A)(this.Kr,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.Ox=function(){return this.g};
g.h.YK=function(a){this.fa()||a||(O6(this,"Cast session died."),this.qd())};g.B(R6,N6);g.h=R6.prototype;g.h.ip=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.wh=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.xa;g.as(this.C);this.A?this.A.stop((0,g.A)(this.qd,this,null),(0,g.A)(this.qd,this,"Failed to stop DIAL device.")):this.qd()};
g.h.U=function(){this.g();this.g=g.xa;g.as(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;R6.ua.U.call(this)};
g.h.bL=function(a){this.fa()||a||(O6(this,"DIAL session died."),this.g(),this.g=g.xa,this.qd())};
g.h.un=function(a){this.K=N4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,T6(this));a(b);S6(this)}else this.F=(0,g.A)(function(){g.as(this.C);this.F=g.xa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,T6(this));a(b);S6(this)},this),this.C=g.Zr((0,g.A)(function(){this.F()},this),100)};
g.h.PA=function(a,b,c){J6(this.J,this.G.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Zk(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.un(b,c)},this),(0,g.A)(function(a){O6(this,"Failed to get DIAL screen: "+a);
this.un(b,c)},this))};g.B(U6,N6);U6.prototype.stop=function(){this.qd()};
U6.prototype.ip=g.xa;U6.prototype.wh=function(){g.as(this.g);this.g=window.NaN;var a=P4(this.J.md(),this.l.label);a?this.Zk(a):this.qd(Error("No such screen"))};
U6.prototype.U=function(){g.as(this.g);this.g=window.NaN;U6.ua.U.call(this)};g.B(V6,g.O);g.h=V6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.Bv,this),(0,g.A)(this.pI,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.zG,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.fa()||(window.chrome.cast.addReceiverActionListener(this.A),uka(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.Nx,this)),this.o=$6(this),window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(a){this.Ab("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.P("yt-remote-cast2-availability-change",Y6(this)),b(!0))},this),(0,g.A)(function(a){this.Ab("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.jK=function(a,b){X6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)X6("Unsetting old screen status: "+this.g.l.friendlyName),Z6(this,null)}if(a&&b){if(!this.g){c=P4(this.l.md(),a);if(!c){X6("setConnectedScreenStatus: Unknown screen.");return}var d=W6(this,c);d||(X6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(a){this.Ab("Failed to set initial custom receivers: "+g.Ig(a))},this)));
X6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);Z6(this,new U6(this.l,d),!0)}this.g.jp(b)}else X6("setConnectedScreenStatus: no screen.")};
g.h.kK=function(a){this.fa()?this.Ab("Setting connection data on disposed cast v2"):this.g?this.g.wh(a):this.Ab("Setting connection data without a session")};
g.h.aL=function(){this.fa()?this.Ab("Stopping session on disposed cast v2"):this.g?(this.g.stop(),Z6(this,null)):X6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.Bv,this),(0,g.A)(this.LI,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.Nx,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Xa(g.z("yt.mdx.remote.debug.handlers_")||[],m6);g.Ve(this.g);V6.ua.U.call(this)};
g.h.Ab=function(a){q6("Controller",a)};
g.h.Cv=function(a,b){this.g==a&&(b||Z6(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.lI=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),X6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)X6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{X6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:Z6(this,
new U6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:Z6(this,new R6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:Z6(this,new Q6(this.l,a));break;default:this.Ab("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Ab("Stopping receiver w/o session: "+a.friendlyName)}else this.Ab("onReceiverAction_ called without receiver.")};
g.h.zG=function(a){if(this.fa())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Ab("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Ab("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return X6("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Ab('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);Z6(this,new R6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.PA,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.un,b))};
g.h.Bv=function(a){if(!this.fa()){X6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)X6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),Z6(this,new Q6(this.l,b),!0);else{this.Ab("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=P4(this.l.md(),c.label);
d&&I4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(X6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ve(this.g),this.g=new Q6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.Cv,this,this.g)),this.g.wh(null));this.g.ip(a)}}};
g.h.ZK=function(){return this.g?this.g.Ox():null};
g.h.LI=function(a){this.fa()||(this.Ab("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&Z6(this,null))};
g.h.pI=function(a){X6("Receiver availability updated: "+a);if(!this.fa()){var b=Y6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;Y6(this)!=b&&this.P("yt-remote-cast2-availability-change",Y6(this))}};
g.h.Nx=function(){this.fa()||(this.o=$6(this),X6("Updating custom receivers: "+g.Ig(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(){this.Ab("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",Y6(this)))};
V6.prototype.setLaunchParams=V6.prototype.kK;V6.prototype.setConnectedScreenStatus=V6.prototype.jK;V6.prototype.stopSession=V6.prototype.aL;V6.prototype.getCastSession=V6.prototype.ZK;V6.prototype.requestSession=V6.prototype.requestSession;V6.prototype.init=V6.prototype.init;V6.prototype.dispose=V6.prototype.dispose;var i7=[];q7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";r7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.ne=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
q7.prototype.isAdPlaying=function(){return 1081==this.g};
q7.prototype.clone=function(){return new q7(w7(this))};g.B(z7,g.O);g.h=z7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.xa,H7(this,"play")):F7(this,"play"),E7(this,1,u7(A7(this))),this.P("remotePlayerChange")):C7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.xa,H7(this,"pause")):F7(this,"pause"),E7(this,2,u7(A7(this))),this.P("remotePlayerChange")):C7(this,this.pause)};
g.h.Jx=function(a){if(1==this.g){if(this.l){var b=A7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.xa,H7(this,"seekTo",{newTime:a}))}else F7(this,"seekTo",{newTime:a});E7(this,3,a);this.P("remotePlayerChange")}else C7(this,g.Ja(this.Jx,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.xa,H7(this,"stopVideo")):F7(this,"stopVideo");var a=A7(this);a.index=-1;a.videoId="";r7(a);D7(this,a);this.P("remotePlayerChange")}else C7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=A7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){q6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Ab("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){q6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Ab("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F7(this,"setVolume",e)}c.muted=b;c.volume=a;D7(this,c)}else C7(this,g.Ja(this.setVolume,a,b))};
g.h.Jw=function(a,b){if(1==this.g){var c=A7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.oc(d,c.l));F7(this,"setSubtitlesTrack",d);D7(this,c)}else C7(this,g.Ja(this.Jw,a,b))};
g.h.Gp=function(a,b){if(1==this.g){F7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ya.id});var c=A7(this);c.audioTrackId=b.Ya.id;D7(this,c)}else C7(this,g.Ja(this.Gp,a,b))};
g.h.Ix=function(a,b){if(1==this.g){if(a&&b){var c=A7(this);v7(c,a,b);D7(this,c)}F7(this,"previous")}else C7(this,g.Ja(this.Ix,a,b))};
g.h.Hx=function(a,b){if(1==this.g){if(a&&b){var c=A7(this);v7(c,a,b);D7(this,c)}F7(this,"next")}else C7(this,g.Ja(this.Hx,a,b))};
g.h.mr=function(){1==this.g?F7(this,"dismissAutoplay"):C7(this,this.mr)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}z7.ua.dispose.call(this)};
g.h.U=function(){B7(this);this.A=null;this.B.clear();y7(this,null);z7.ua.U.call(this)};
g.h.Hp=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.hI=function(a,b){this.P(a,b)};
g.h.dG=function(a){if(!a)this.Yi(null),y7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=A7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)q6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D7(this,b)}};
g.h.Yi=function(a){q6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),G7(this),this.P("remotePlayerChange")};
g.h.cG=function(a){a?(G7(this),this.P("remotePlayerChange")):this.Yi(null)};
g.h.pG=function(){var a=m7();a&&y7(this,a)};
g.h.Ab=function(a){q6("CP",a)};g.B(I7,g.O);g.h=I7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Ja.listId=c);this.Ja.videoId=d;this.Ja.index=k||0;this.Ja.state=3;t7(this.Ja,m);this.A="UNSUPPORTED";J7("Connecting with setPlaylist and params: "+g.Ig(l));this.g.connect({method:"setPlaylist",params:g.Ig(l)},
a,V4())}else J7("Connecting without params"),this.g.connect({},a,V4());Kka(this)};
g.h.dispose=function(){this.fa()||(this.P("beforeDispose"),K7(this,3));I7.ua.dispose.call(this)};
g.h.U=function(){L7(this);N7(this);M7(this);g.as(this.J);this.J=window.NaN;g.as(this.K);this.K=window.NaN;this.o=null;g.At(this.T);this.T.length=0;this.g.dispose();I7.ua.U.call(this);this.A=this.F=this.l=this.Ja=this.g=null};
g.h.Zz=function(){this.C(2)};
g.h.hG=function(){J7("Channel opened");this.R&&(this.R=!1,M7(this),this.O=g.Zr((0,g.A)(function(){J7("Timing out waiting for a screen.");this.C(1)},this),15E3));
hka(ska(this.g),this.X)};
g.h.eG=function(){J7("Channel closed");(0,window.isNaN)(this.B)?Y4(!0):Y4();this.dispose()};
g.h.fG=function(a){Y4();(0,window.isNaN)(this.G())?(J7("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,J7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),K7(this,2))};
g.h.gG=function(a){a.params?J7("Received: action="+a.action+", params="+g.Ig(a.params)):J7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Hq(a.params.devices);this.l=(0,g.E)(a,function(a){return new G4(a)});
a=!!g.Pa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Q7(this,a);break;case "loungeScreenDisconnected":g.Ya(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Q7(this,!1);break;case "remoteConnected":var b=new G4(g.Hq(a.params.device));g.Pa(this.l,function(a){return b?a.id==b.id:!1})||g.Va(this.l,b);
break;case "remoteDisconnected":b=new G4(g.Hq(a.params.device));g.Ya(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":R7(this,a);break;case "nowPlaying":Nka(this,a);break;case "onStateChange":S7(this,a);break;case "onAdStateChange":Oka(this,a);break;case "onVolumeChanged":Pka(this,a);break;case "onSubtitlesTrackChanged":Mka(this,a);break;case "nowAutoplaying":Qka(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.P("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Rka(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:J7("Unrecognized action: "+a.action)}};
g.h.XJ=function(){if(this.o){var a=this.o;this.o=null;this.Ja.videoId!=a&&O7(this,"getNowPlaying")}};
I7.prototype.subscribe=I7.prototype.subscribe;I7.prototype.unsubscribeByKey=I7.prototype.Bc;I7.prototype.ha=function(){var a=3;this.fa()||(a=0,(0,window.isNaN)(this.G())?i6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
I7.prototype.getProxyState=I7.prototype.ha;I7.prototype.C=function(a){J7("Disconnecting with "+a);L7(this);this.P("beforeDisconnect",a);1==a&&Y4();h6(this.g,a);this.dispose()};
I7.prototype.disconnect=I7.prototype.C;I7.prototype.ea=function(){var a=this.Ja;this.o&&(a=this.Ja.clone(),v7(a,this.o,a.index));return w7(a)};
I7.prototype.getPlayerContextData=I7.prototype.ea;
I7.prototype.na=function(a){var b=new q7(a);b.videoId&&b.videoId!=this.Ja.videoId&&(this.o=b.videoId,g.as(this.J),this.J=g.Zr((0,g.A)(this.XJ,this),5E3));var c=[];this.Ja.listId==b.listId&&this.Ja.videoId==b.videoId&&this.Ja.index==b.index||c.push("remoteQueueChange");this.Ja.g==b.g&&this.Ja.volume==b.volume&&this.Ja.muted==b.muted&&u7(this.Ja)==u7(b)&&g.Ig(this.Ja.l)==g.Ig(b.l)||c.push("remotePlayerChange");this.Ja.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
I7.prototype.setPlayerContextData=I7.prototype.na;I7.prototype.Y=function(){var a=this.g.C.id,b=g.Pa(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
I7.prototype.getOtherConnectedRemoteId=I7.prototype.Y;I7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.D)():window.NaN};
I7.prototype.getReconnectTimeout=I7.prototype.G;I7.prototype.W=function(){return this.A||"UNSUPPORTED"};
I7.prototype.getAutoplayMode=I7.prototype.W;I7.prototype.ca=function(){return this.F||""};
I7.prototype.getAutoplayVideoId=I7.prototype.ca;I7.prototype.va=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.xq(a.g);a.start()}};
I7.prototype.reconnect=I7.prototype.va;I7.prototype.la=function(a,b){O7(this,a,b);P7(this)};
I7.prototype.sendMessage=I7.prototype.la;g.B(T7,u6);g.h=T7.prototype;g.h.md=function(a){return this.xc.$_gs(a)};
g.h.contains=function(a){return!!this.xc.$_c(a)};
g.h.get=function(a){return this.xc.$_g(a)};
g.h.start=function(){this.xc.$_st()};
g.h.add=function(a,b,c){this.xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.xc.$_r(a,b,c)};
g.h.Kl=function(a,b,c,d){this.xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.xc.$_ubk(this.l[a]);this.l.length=0;this.xc=null;T7.ua.U.call(this)};
g.h.WK=function(){this.P("screenChange")};
g.h.OH=function(){this.P("onlineScreenChange")};
H6.prototype.$_st=H6.prototype.start;H6.prototype.$_gspc=H6.prototype.XK;H6.prototype.$_gsppc=H6.prototype.Mx;H6.prototype.$_c=H6.prototype.contains;H6.prototype.$_g=H6.prototype.get;H6.prototype.$_a=H6.prototype.add;H6.prototype.$_un=H6.prototype.Kl;H6.prototype.$_r=H6.prototype.remove;H6.prototype.$_gs=H6.prototype.md;H6.prototype.$_gos=H6.prototype.Lx;H6.prototype.$_s=H6.prototype.subscribe;H6.prototype.$_ubk=H6.prototype.Bc;var U7=null,V7=null,k8=null,Z7=[];g.r(n8,g.G);g.h=n8.prototype;
g.h.U=function(){g.G.prototype.U.call(this);this.A.stop();this.B.stop();this.L.stop();this.R();this.g.unsubscribe("proxyStateChange",this.zv,this);this.g.unsubscribe("remotePlayerChange",this.Zi,this);this.g.unsubscribe("remoteQueueChange",this.al,this);this.g.unsubscribe("autoplayUpNext",this.Wu,this);this.g.unsubscribe("previousNextChange",this.wv,this);this.g.unsubscribe("nowAutoplaying",this.rv,this);this.g.unsubscribe("autoplayDismissed",this.Vu,this);this.g=this.G=null};
g.h.Xt=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(r8(this)){if(!A7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==A7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.K.mh(c[0],c[1]);break;case "control_subtitles_set_track":s8(this,c[0]);break;case "control_set_audio_track":c=c[0],r8(this)&&this.g.Gp(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();t8(this,0==c?void 0:c);break;case "control_seek":t8(this,c[0]);break;case "control_subtitles_set_track":s8(this,c[0]);break;case "control_set_audio_track":c=c[0],r8(this)&&this.g.Gp(this.l.getVideoData(1).videoId,c)}};
g.h.bG=function(a){this.L.Uz(a)};
g.h.DK=function(a){this.Xt("control_subtitles_set_track",g.gc(a)?null:a)};
g.h.Vw=function(){var a=this.l.Nb("captions","track");g.gc(a)||s8(this,a)};
g.h.ov=function(a){if(r8(this)){this.g.unsubscribe("remotePlayerChange",this.Zi,this);var b=Math.round(a.volume);a=!!a.muted;var c=A7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.O.start();this.g.subscribe("remotePlayerChange",this.Zi,this)}};
g.h.hH=function(){g.gc(this.C)||u8(this,this.C);this.F=!1};
g.h.zv=function(a,b){this.B.stop();2==b&&this.Tw()};
g.h.Zi=function(){if(r8(this)){this.A.stop();var a=A7(this.g);switch(a.g){case 1081:case 1:p8(this,new g.QD(8));this.Sw();break;case 1085:case 3:p8(this,new g.QD(9));break;case 1083:case 0:p8(this,new g.QD(2));this.K.stop();o8(this,this.l.getVideoData().lengthSeconds);break;case 1084:p8(this,new g.QD(4));break;case 2:p8(this,new g.QD(4));o8(this,u7(a));break;case -1:p8(this,new g.QD(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.Q("YTP_MDX_PLAYER_ERROR")},p8(this,new g.QD(128,a))}a=
A7(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,u8(this,a));a=A7(this.g);-1==a.volume||Math.round(this.l.Mb())==a.volume&&this.l.isMuted()==a.muted||this.O.isActive()||this.zx()}else q8(this)};
g.h.wv=function(){this.l.P("mdxpreviousnextchange")};
g.h.al=function(){r8(this)||q8(this)};
g.h.qz=function(){this.g.mr()};
g.h.Wu=function(a){a&&(a=g.ps("/watch_queue_ajax",{method:"GET",tc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.lJ,this)}))&&(this.R=(0,g.A)(a.abort,a))};
g.h.lJ=function(a,b){var c=new g.FC({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.rv=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.Vu=function(){this.l.P("mdxautoplaycanceled")};
g.h.QD=function(a,b){-1==A7(this.g).g?t8(this,a):b&&this.g.Jx(a)};
g.h.zx=function(){if(r8(this)){var a=A7(this.g);this.o.Oa(this.T);a.muted?this.l.mute():this.l.ye();this.l.setVolume(a.volume);this.T=this.o.M(this.l,"onVolumeChange",this.ov)}};
g.h.Sw=function(){this.A.stop();if(!this.g.fa()){var a=A7(this.g);1==a.g&&p8(this,new g.QD(8));o8(this,u7(a));this.A.start()}};
g.h.Tw=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(x8,g.R);x8.prototype.A=function(a){w8(this,a.state)};g.r(y8,g.NT);y8.prototype.K=function(){var a=this.l.Nb("remote","receivers");a&&1<a.length&&!this.l.Nb("remote","quickCast")?(this.G=g.pb(a,this.B,this),g.OT(this,(0,g.E)(a,this.B)),a=this.l.Nb("remote","currentReceiver"),this.Yd(this.B(a)),this.enable(!0)):this.enable(!1)};
y8.prototype.B=function(a){return a.key};
y8.prototype.Xd=function(a){return"cast-selector-receiver"==a?g.Q("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
y8.prototype.Hc=function(a){g.NT.prototype.Hc.call(this,a);this.l.Sc("remote","currentReceiver",this.G[a]);this.A.kb()};g.r(z8,g.RK);g.h=z8.prototype;g.h.create=function(){Wka(g.UA(g.V(this.g)));this.C.push(g.$t("yt-remote-before-disconnect",this.YF,this));this.C.push(g.$t("yt-remote-connection-change",this.qI,this));this.C.push(g.$t("yt-remote-receiver-availability-change",this.xv,this));this.C.push(g.$t("yt-remote-auto-connect",this.oI,this));this.C.push(g.$t("yt-remote-receiver-resumed",this.nI,this));this.xv()};
g.h.load=function(){this.g.ho();g.RK.prototype.load.call(this);this.B=new n8(this,this.g,this.l);var a=(a=m8())?a.currentTime:0;var b=j8()?new z7(e8(),void 0):null;0==a&&b&&(a=u7(A7(b)));0!=a&&(this.J=a||0,this.g.P("progresssync",a,void 0));v8(this,this.F,this.F);g.JV(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.We(this.B,this.l);this.l=this.B=null;g.RK.prototype.unload.call(this);g.JV(this.g.app,5)};
g.h.U=function(){g.au(this.C);g.RK.prototype.U.call(this)};
g.h.Qi=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Xt.apply(this.B,[a].concat(g.oa(c)))};
g.h.Rz=function(){return this.loaded?this.B.suggestion:null};
g.h.ne=function(){return this.l?A7(this.l).ne:!1};
g.h.hasNext=function(){return this.l?A7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.GD=function(){var a=A7(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.yc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.C?a.J+s7(a):a.J,ingestionTime:a.C?a.A+s7(a):a.A,isPeggedToLive:1>=(a.C?a.o+s7(a):a.o)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.C?a.o+s7(a):a.o,seekableStart:0<a.B?a.B+s7(a):a.B}};
g.h.HD=function(){this.l&&this.l.Hx()};
g.h.ID=function(){this.l&&this.l.Ix()};
g.h.YF=function(a){1==a&&(this.K=this.l?A7(this.l):null)};
g.h.qI=function(){var a=j8()?new z7(e8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.K=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ve(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.getVideoData().videoId&&this.g.Ct(a.videoId,u7(a)));this.g.P("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.xv=function(){this.G=[this.o].concat(Xka());var a=f8()||this.o;A8(this,a);this.g.ka("onMdxReceiversChange")};
g.h.oI=function(){var a=f8();A8(this,a)};
g.h.nI=function(){this.A=f8()};
g.h.FD=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?o7():A8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&o7(),!0):!1}};
g.h.JD=function(){F7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Zb=function(){return!1};g.UQ.remote=z8;})(_yt_player);
